menu:
- {name: 'Research', url: '/publications'}
- {name: 'Teaching', url: '/courses'}
- {name: 'References', url: '/contact'}

courses:
- {name: 'Econometric Methods', url: 'vector-calculus'}
- {name: 'Machine Learining for Economics', url: 'quantum-mechanics'}

social:
- {icon: 'github', link: 'https://albertoc94.github.io/albertocappello/'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/alberto-cappello/'}

contacts:
- {name: 'Michael Grubb', institution: 'Boston College', email: 'michael.grubb@bc.edu'}
- {name: 'Richard Sweeney', institution: 'Boston College', email: 'sweeneri@bc.edu'}
- {name: 'Diana Bowser', institution: 'Boston College', email: 'bowserdi@bc.edu'}
