menu:
- {name: 'Home', url: '/'}
- {name: 'Research', url: '/research'}
- {name: 'Teaching', url: '/courses'}
- {name: 'Contact', url: '/contact'}

fields:
- 'Industrial Organization'
- 'Health Economics'
- 'Applied Econometrics'

courses:
- name: 'Machine Learning for Economics'
  url: 'machine-learning-for-economics'
  institution: 'Boston College'
  term: 'Fall 2024'
  role: 'Instructor'
- name: 'Econometric Methods'
  url: 'econometric-methods'
  institution: 'Boston College'
  role: 'Instructor'

contacts:
- {name: 'Michael Grubb', institution: 'Boston College', email: 'michael.grubb@bc.edu'}
- {name: 'Richard Sweeney', institution: 'Boston College', email: 'sweeneri@bc.edu'}
- {name: 'Diana Bowser', institution: 'Boston College', email: 'bowserdi@bc.edu'}
